### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by cedenoruel** [mspillman/gallop#3]
Hi Gallop developers! I'm getting this error when using the web-based program with default settings.

```
IndexError: list index out of range
Traceback:
File "/usr/local/lib/python3.7/dist-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/content/gallop/gallop_streamlit.py", line 150, in <module>
    struct.add_restraint(atom1=r[0], atom2=r[1],
```
Attached here are my zmat and dash-generated files.
[gallop_monoclinic.zip](https://github.com/mspillman/gallop/files/7273192/gallop_monoclinic.zip)

Thank you very much in advance.

**Comment by mspillman** [comment]
Hello, sorry to hear about the error.

How did you install GALLOP? I am not able to replicate your error with the data you provided.

If running GALLOP on your local machine, please try uninstalling the program, then reinstall using the updated installation instructions for Conda (see Readme).

If running GALLOP on a remote cloud GPU, can you provide information as to which service you are using so I can try to replicate the issue? Thanks!

**Comment by mspillman** [comment]
Marking this as closed as no response for two weeks. If the issue comes up again, please open a new issue and I will investigate further. Thank you!
